version: '2'
services:
    reports-app:
        image: reports
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://reports-mariadb:3306/reports
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reports-mariadb:
        extends:
            file: mariadb.yml
            service: reports-mariadb
